[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
primaryColor = "#d4a017"
backgroundColor = "#ebe6df"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1510"
font = "sans serif"
